package com.example.ui

import java.util.Locale

data class AppStrings(
    // Bottom Bar
    val home: String,
    val documents: String,
    val tools: String,
    val settings: String,

    // Header & Greeting
    val goodMorning: String,
    val goodEvening: String,
    val welcomeMessage: String,
    val statsTitle: String,
    val sortTitle: String,

    // Search & Filter
    val searchPlaceholder: String,
    val recent: String,
    val favorites: String,
    val allDocs: String,

    // Empty States & Search
    val emptyLibraryTitle: String,
    val emptyLibrarySubtitle: String,
    val noSearchResultsTitle: String,
    val noSearchResultsSubtitle: String,

    // Stats Card & Stats Sheet
    val totalFiles: String,
    val favoriteFiles: String,
    val openedFiles: String,
    val readingHours: String,
    val missingFiles: String,
    val totalPdfs: String,
    val totalFolders: String,
    val documentSize: String,
    val libraryOverviewSubtitle: String,

    // Folders
    val sampleFiles: String,
    val pdfFiles: String,
    val folders: String,
    val sampleDocumentTitle: String,
    val importedDocuments: String,
    val unknown: String,
    val fileCountFormat: (Int) -> String,

    // Tools Tab
    val toolsTitle: String,
    val toolsSubtitle: String,
    val cameraOcrTitle: String,
    val cameraOcrDesc: String,
    val cloudOcrTitle: String,
    val cloudOcrDesc: String,
    val mergePdfTitle: String,
    val mergePdfDesc: String,
    val splitPdfTitle: String,
    val splitPdfDesc: String,
    val compressPdfTitle: String,
    val compressPdfDesc: String,
    val rotatePdfTitle: String,
    val rotatePdfDesc: String,
    val reorderPdfTitle: String,
    val reorderPdfDesc: String,
    val deletePdfTitle: String,
    val deletePdfDesc: String,

    // Settings Tab
    val appearanceSection: String,
    val appThemeTitle: String,
    val appLanguageTitle: String,
    val showToolsTabTitle: String,
    val showToolsTabSubtitle: String,
    val readerDisplaySection: String,
    val scrollDirectionTitle: String,
    val defaultZoomTitle: String,
    val doubleTapZoomTitle: String,
    val readingThemeTitle: String,

    // Sort Sheet
    val sortSubtitle: String,
    val sortAlphabetical: String,
    val sortAlphaAsc: String,
    val sortAlphaDesc: String,
    val sortFileSizeLabel: String,
    val sortSizeAsc: String,
    val sortSizeDesc: String,
    val sortDateAddedLabel: String,
    val sortDateAsc: String,
    val sortDateDesc: String,

    // File Action Sheet & Details
    val quickActions: String,
    val addToFav: String,
    val removeFromFav: String,
    val addToFavDesc: String,
    val removeFromFavDesc: String,
    val selectFile: String,
    val selectFileDesc: String,
    val shareFile: String,
    val shareFileDesc: String,
    val renameFile: String,
    val renameFileDesc: String,
    val fileInfo: String,
    val fileInfoDesc: String,
    val deleteFile: String,
    val deleteFileDesc: String,
    val openDocument: String,
    val share: String,
    val copyPath: String,
    val pathCopied: String,
    val fullPath: String,
    val folderName: String,
    val storageLocationSection: String,
    val pdfVersion: String,
    val encryption: String,
    val encrypted: String,
    val notEncrypted: String,
    val authorSection: String,
    val authorLabel: String,
    val documentTitleLabel: String,
    val subjectLabel: String,
    val keywordsLabel: String,
    val datesSection: String,
    val creationDate: String,
    val modificationDate: String,
    val creatorAppSection: String,
    val creatorLabel: String,
    val producerLabel: String,
    val extractingMetadata: String,

    // Viewer Screen & Reader Tabs
    val pagesTab: String,
    val viewTab: String,
    val zoomTab: String,
    val themesTab: String,
    val bookmarkTab: String,
    val moreTab: String,
    val searchInPdf: String,
    val jumpToPage: String,
    val tableOfContents: String,
    val readAloud: String,
    val autoScroll: String,
    val cropPages: String,
    val ocrExtract: String,
    val notesHighlights: String,
    val exportImage: String,
    val printDocument: String,
    val fitWidth: String,
    val fitPage: String,
    val actualSize: String,
    val themeLight: String,
    val themeDark: String,
    val themeSepia: String,
    val themeAmoled: String,
    val goButton: String,
    val closeButton: String,
    val cancelButton: String,
    val saveButton: String,
    val confirmButton: String,

    // Camera OCR
    val cameraPermissionTitle: String,
    val cameraPermissionDesc: String,
    val grantPermission: String,
    val copyText: String,
    val singleMode: String,
    val batchMode: String,
    val importFiles: String,
    val importImages: String,

    // Exit App Dialog
    val exitAppTitle: String,
    val exitAppSubtitle: String,
    val exitAppConfirm: String,

    // Additional UI Strings
    val selectFromLibrary: String,
    val internalStorage: String,
    val processSuccess: String,
    val fileSavedInFinalPDF: String,
    val autoSystem: String,
    val verticalScroll: String,
    val horizontalScroll: String,
    val portraitMode: String,
    val landscapeMode: String,
    val useSystemBrightness: String,

    // Lock, Unlock & Extra
    val lockPdfTitle: String,
    val lockPdfDesc: String,
    val unlockPdfTitle: String,
    val unlockPdfDesc: String,
    val confirm: String,
    val noPdfSelected: String,
    val noPdfFound: String
)

object AppStringsProvider {
    fun get(languageCode: String): AppStrings {
        val lang = if (languageCode == "auto") {
            Locale.getDefault().language
        } else {
            languageCode
        }

        return when (lang) {
            "en" -> AppStrings(
                home = "Home",
                documents = "Documents",
                tools = "Tools",
                settings = "Settings",
                goodMorning = "Good morning!",
                goodEvening = "Good evening!",
                welcomeMessage = "Welcome to FinalPDF",
                statsTitle = "Library Stats",
                sortTitle = "Sort Files",
                searchPlaceholder = "Search PDF files...",
                recent = "Recent",
                favorites = "Favorites",
                allDocs = "All Docs",
                emptyLibraryTitle = "Your library is empty",
                emptyLibrarySubtitle = "Tap (+) to open and read your first PDF file.",
                noSearchResultsTitle = "No matching search results",
                noSearchResultsSubtitle = "Check the file name and try searching again.",
                totalFiles = "Total Files",
                favoriteFiles = "Favorite Files",
                openedFiles = "Opened Files",
                readingHours = "Reading Time",
                missingFiles = "Missing Files",
                totalPdfs = "PDFs",
                totalFolders = "Folders",
                documentSize = "Document Size",
                libraryOverviewSubtitle = "Overview of files and reading activity in your library",
                sampleFiles = "Sample Files",
                pdfFiles = "PDF Files",
                folders = "Folders",
                sampleDocumentTitle = "Sample Document (14 pages)",
                importedDocuments = "Imported Documents",
                unknown = "Unknown",
                fileCountFormat = { count -> "$count PDF${if (count != 1) "s" else ""}" },
                toolsTitle = "Advanced PDF Tools",
                toolsSubtitle = "Smart tools to edit, convert, and manage your PDFs",
                cameraOcrTitle = "Camera OCR Scanner",
                cameraOcrDesc = "Capture documents and extract text instantly",
                cloudOcrTitle = "PDF to Text (OCR)",
                cloudOcrDesc = "Convert scanned PDF pages into editable text",
                mergePdfTitle = "Merge PDF Files",
                mergePdfDesc = "Combine multiple PDFs into a single file",
                splitPdfTitle = "Split PDF File",
                splitPdfDesc = "Extract specific pages into a new PDF",
                compressPdfTitle = "Compress PDF",
                compressPdfDesc = "Reduce file size for easier sharing",
                rotatePdfTitle = "Rotate Pages",
                rotatePdfDesc = "Rotate selected or all pages in PDF",
                reorderPdfTitle = "Reorder Pages",
                reorderPdfDesc = "Drag and rearrange PDF pages",
                deletePdfTitle = "Delete Pages",
                deletePdfDesc = "Remove unwanted pages from PDF",
                appearanceSection = "APPEARANCE",
                appThemeTitle = "App Theme",
                appLanguageTitle = "App & Recognition Language",
                showToolsTabTitle = "Show Tools Tab",
                showToolsTabSubtitle = "Show or hide tools tab in bottom bar",
                readerDisplaySection = "READER & DISPLAY",
                scrollDirectionTitle = "Scroll Direction",
                defaultZoomTitle = "Default Zoom Level",
                doubleTapZoomTitle = "Double Tap Zoom",
                readingThemeTitle = "Reading Background Theme",
                sortSubtitle = "Choose how to organize and view your PDF files",
                sortAlphabetical = "Alphabetical",
                sortAlphaAsc = "A -> Z  ↑",
                sortAlphaDesc = "Z -> A  ↓",
                sortFileSizeLabel = "File Size",
                sortSizeAsc = "Smallest First  ↑",
                sortSizeDesc = "Largest First  ↓",
                sortDateAddedLabel = "Date Added",
                sortDateAsc = "Oldest First  ↑",
                sortDateDesc = "Newest First  ↓",
                quickActions = "Quick Actions",
                addToFav = "Add to Favorites",
                removeFromFav = "Remove from Favorites",
                addToFavDesc = "Save to your favorites for quick access",
                removeFromFavDesc = "Remove from your favorite files list",
                selectFile = "Select File",
                selectFileDesc = "Enter multi-selection mode for this file",
                shareFile = "Share File",
                shareFileDesc = "Send this PDF to other applications",
                renameFile = "Rename",
                renameFileDesc = "Change the document title or file name",
                fileInfo = "File Info",
                fileInfoDesc = "View detailed properties and metadata",
                deleteFile = "Delete File",
                deleteFileDesc = "Remove file from device or library",
                openDocument = "Open Document",
                share = "Share",
                copyPath = "Copy Path",
                pathCopied = "File path copied to clipboard",
                fullPath = "Full Path:",
                folderName = "Folder Name",
                storageLocationSection = "Location & Storage",
                pdfVersion = "PDF Version",
                encryption = "Security",
                encrypted = "Password Protected",
                notEncrypted = "Unprotected",
                authorSection = "Author & Document Details",
                authorLabel = "Author / Writer",
                documentTitleLabel = "Document Title",
                subjectLabel = "Subject",
                keywordsLabel = "Keywords",
                datesSection = "Dates & Time",
                creationDate = "Creation Date",
                modificationDate = "Last Modified",
                creatorAppSection = "Creator & Engine",
                creatorLabel = "Creator Tool",
                producerLabel = "PDF Producer",
                extractingMetadata = "Extracting document properties and metadata...",
                pagesTab = "Pages",
                viewTab = "View",
                zoomTab = "Zoom",
                themesTab = "Themes",
                bookmarkTab = "Bookmark",
                moreTab = "Tools",
                searchInPdf = "Search in PDF",
                jumpToPage = "Jump to Page",
                tableOfContents = "Table of Contents",
                readAloud = "Read Aloud (TTS)",
                autoScroll = "Auto Scroll",
                cropPages = "Crop Pages",
                ocrExtract = "Extract Text (OCR)",
                notesHighlights = "Notes & Highlights",
                exportImage = "Export as Image",
                printDocument = "Print Document",
                fitWidth = "Fit Width",
                fitPage = "Fit Page",
                actualSize = "100% Actual Size",
                themeLight = "Light Canvas",
                themeDark = "Dark Mode",
                themeSepia = "Warm Sepia",
                themeAmoled = "OLED Pitch Black",
                goButton = "Go",
                closeButton = "Close",
                cancelButton = "Cancel",
                saveButton = "Save",
                confirmButton = "Confirm",
                cameraPermissionTitle = "Camera Permission Required",
                cameraPermissionDesc = "Camera access is needed to scan documents and extract text.",
                grantPermission = "Grant Camera Permission",
                copyText = "Copy Text",
                singleMode = "Single",
                batchMode = "Batch",
                importFiles = "Import Files",
                importImages = "Import Images",
                exitAppTitle = "Exit FinalPDF?",
                exitAppSubtitle = "Are you sure you want to exit the application?",                exitAppConfirm = "Exit App",
                selectFromLibrary = "Choose from Local Library",
                internalStorage = "Internal Storage",
                processSuccess = "Process completed successfully!",
                fileSavedInFinalPDF = "File saved successfully in FinalPDF folder",
                autoSystem = "Auto (System)",
                verticalScroll = "Vertical Scroll",
                horizontalScroll = "Horizontal Scroll",
                portraitMode = "Portrait",
                landscapeMode = "Landscape",
                useSystemBrightness = "Use System Brightness",
                lockPdfTitle = "Protect & Lock PDF",
                lockPdfDesc = "Protect document with password encryption",
                unlockPdfTitle = "Unlock & Remove PDF Security",
                unlockPdfDesc = "Remove password protection from encrypted PDF",
                confirm = "Confirm",
                noPdfSelected = "No PDF file selected",
                noPdfFound = "No PDF files found"
            )
            "fr" -> AppStrings(
                home = "Accueil",
                documents = "Documents",
                tools = "Outils",
                settings = "Paramètres",
                goodMorning = "Bonjour !",
                goodEvening = "Bonsoir !",
                welcomeMessage = "Bienvenue sur FinalPDF",
                statsTitle = "Statistiques de la bibliothèque",
                sortTitle = "Trier les fichiers",
                searchPlaceholder = "Rechercher des fichiers PDF...",
                recent = "Récents",
                favorites = "Favoris",
                allDocs = "Tous les docs",
                emptyLibraryTitle = "Votre bibliothèque est vide",
                emptyLibrarySubtitle = "Appuyez sur (+) pour ouvrir votre premier PDF.",
                noSearchResultsTitle = "Aucun résultat trouvé",
                noSearchResultsSubtitle = "Vérifiez le nom du fichier et réessayez.",
                totalFiles = "Total Fichiers",
                favoriteFiles = "Favoris",
                openedFiles = "Fichiers Ouverts",
                readingHours = "Temps de lecture",
                missingFiles = "Fichiers manquants",
                totalPdfs = "PDFs",
                totalFolders = "Dossiers",
                documentSize = "Taille des documents",
                libraryOverviewSubtitle = "Aperçu de vos documents et activités de lecture",
                sampleFiles = "Fichiers d'exemple",
                pdfFiles = "Fichiers PDF",
                folders = "Dossiers",
                sampleDocumentTitle = "Document d'exemple (14 pages)",
                importedDocuments = "Documents importés",
                unknown = "Inconnu",
                fileCountFormat = { count -> "$count PDF${if (count > 1) "s" else ""}" },
                toolsTitle = "Outils PDF Avancés",
                toolsSubtitle = "Des outils intelligents pour éditer et gérer vos PDF",
                cameraOcrTitle = "Scanner OCR Caméra",
                cameraOcrDesc = "Numérisez des documents et extrayez le texte",
                cloudOcrTitle = "PDF en texte (OCR)",
                cloudOcrDesc = "Convertissez des pages numérisées en texte",
                mergePdfTitle = "Fusionner les PDF",
                mergePdfDesc = "Combinez plusieurs fichiers PDF en un seul",
                splitPdfTitle = "Diviser le PDF",
                splitPdfDesc = "Extrayez des pages spécifiques dans un nouveau PDF",
                compressPdfTitle = "Compresser le PDF",
                compressPdfDesc = "Réduisez la taille pour un partage facile",
                rotatePdfTitle = "Pivoter les pages",
                rotatePdfDesc = "Pivotez des pages sélectionnées ou toutes",
                reorderPdfTitle = "Réorganiser les pages",
                reorderPdfDesc = "Glissez et réorganisez les pages",
                deletePdfTitle = "Supprimer des pages",
                deletePdfDesc = "Supprimez les pages indésirables du PDF",
                appearanceSection = "APPARENCE",
                appThemeTitle = "Thème de l'application",
                appLanguageTitle = "Langue de l'application",
                showToolsTabTitle = "Afficher l'onglet Outils",
                showToolsTabSubtitle = "Afficher ou masquer l'onglet Outils dans la barre inférieure",
                readerDisplaySection = "LECTURE & AFFICHAGE",
                scrollDirectionTitle = "Sens de défilement",
                defaultZoomTitle = "Zoom par défaut",
                doubleTapZoomTitle = "Zoom double-tape",
                readingThemeTitle = "Thème du fond de lecture",
                sortSubtitle = "Choisissez comment organiser et afficher vos fichiers PDF",
                sortAlphabetical = "Alphabétique",
                sortAlphaAsc = "A -> Z  ↑",
                sortAlphaDesc = "Z -> A  ↓",
                sortFileSizeLabel = "Taille du fichier",
                sortSizeAsc = "Plus petit d'abord  ↑",
                sortSizeDesc = "Plus grand d'abord  ↓",
                sortDateAddedLabel = "Date d'ajout",
                sortDateAsc = "Plus ancien d'abord  ↑",
                sortDateDesc = "Plus récent d'abord  ↓",
                quickActions = "Actions Rapides",
                addToFav = "Ajouter aux Favoris",
                removeFromFav = "Retirer des Favoris",
                addToFavDesc = "Enregistrer dans vos favoris pour un accès rapide",
                removeFromFavDesc = "Retirer de la liste de vos fichiers favoris",
                selectFile = "Sélectionner le fichier",
                selectFileDesc = "Activer le mode sélection multiple pour ce fichier",
                shareFile = "Partager le fichier",
                shareFileDesc = "Envoyer ce PDF à d'autres applications",
                renameFile = "Renommer",
                renameFileDesc = "Changer le titre du document ou le nom",
                fileInfo = "Infos sur le fichier",
                fileInfoDesc = "Afficher les propriétés et métadonnées",
                deleteFile = "Supprimer le fichier",
                deleteFileDesc = "Supprimer le fichier de l'appareil ou de la bibliothèque",
                openDocument = "Ouvrir le document",
                share = "Partager",
                copyPath = "Copier le chemin",
                pathCopied = "Chemin du fichier copié dans le presse-papiers",
                fullPath = "Chemin complet :",
                folderName = "Nom du dossier",
                storageLocationSection = "Emplacement et stockage",
                pdfVersion = "Version PDF",
                encryption = "Sécurité",
                encrypted = "Protégé par mot de passe",
                notEncrypted = "Non protégé",
                authorSection = "Auteur et détails du document",
                authorLabel = "Auteur / Écrivain",
                documentTitleLabel = "Titre du document",
                subjectLabel = "Sujet",
                keywordsLabel = "Mots-clés",
                datesSection = "Dates et heure",
                creationDate = "Date de création",
                modificationDate = "Dernière modification",
                creatorAppSection = "Créateur et moteur",
                creatorLabel = "Logiciel créateur",
                producerLabel = "Producteur PDF",
                extractingMetadata = "Extraction des propriétés du document...",
                pagesTab = "Pages",
                viewTab = "Affichage",
                zoomTab = "Zoom",
                themesTab = "Thèmes",
                bookmarkTab = "Signet",
                moreTab = "Outils",
                searchInPdf = "Rechercher dans le PDF",
                jumpToPage = "Aller à la page",
                tableOfContents = "Table des matières",
                readAloud = "Lecture vocale (TTS)",
                autoScroll = "Défilement auto",
                cropPages = "Rogner les pages",
                ocrExtract = "Extraire le texte (OCR)",
                notesHighlights = "Notes & Surlignages",
                exportImage = "Exporter en image",
                printDocument = "Imprimer le document",
                fitWidth = "Ajuster à la largeur",
                fitPage = "Ajuster à la page",
                actualSize = "Taille réelle 100%",
                themeLight = "Fond Clair",
                themeDark = "Mode Sombre",
                themeSepia = "Sépia Chaud",
                themeAmoled = "Noir OLED",
                goButton = "Aller",
                closeButton = "Fermer",
                cancelButton = "Annuler",
                saveButton = "Enregistrer",
                confirmButton = "Confirmer",
                cameraPermissionTitle = "Autorisation de caméra requise",
                cameraPermissionDesc = "L'accès à la caméra est nécessaire pour scanner des documents.",
                grantPermission = "Accorder l'autorisation",
                copyText = "Copier le texte",
                singleMode = "Unique",
                batchMode = "Lot",
                importFiles = "Importer fichiers",
                importImages = "Importer images",
                exitAppTitle = "Quitter FinalPDF ?",
                exitAppSubtitle = "Êtes-vous sûr de vouloir quitter l'application ?",                exitAppConfirm = "Exit App",
                selectFromLibrary = "Choose from Local Library",
                internalStorage = "Internal Storage",
                processSuccess = "Process completed successfully!",
                fileSavedInFinalPDF = "File saved successfully in FinalPDF folder",
                autoSystem = "Auto (System)",
                verticalScroll = "Vertical Scroll",
                horizontalScroll = "Horizontal Scroll",
                portraitMode = "Portrait",
                landscapeMode = "Landscape",
                useSystemBrightness = "Utiliser la luminosité du système",
                lockPdfTitle = "Protéger et verrouiller le PDF",
                lockPdfDesc = "Protéger le document avec un mot de passe",
                unlockPdfTitle = "Déverrouiller le PDF",
                unlockPdfDesc = "Supprimer la protection par mot de passe",
                confirm = "Confirmer",
                noPdfSelected = "Aucun fichier PDF sélectionné",
                noPdfFound = "Aucun fichier PDF trouvé"
            )
            "de" -> AppStrings(
                home = "Startseite",
                documents = "Dokumente",
                tools = "Werkzeuge",
                settings = "Einstellungen",
                goodMorning = "Guten Morgen!",
                goodEvening = "Guten Abend!",
                welcomeMessage = "Willkommen bei FinalPDF",
                statsTitle = "Bibliotheksstatistik",
                sortTitle = "Dateien sortieren",
                searchPlaceholder = "PDF-Dateien suchen...",
                recent = "Zuletzt",
                favorites = "Favoriten",
                allDocs = "Alle Dok.",
                emptyLibraryTitle = "Ihre Bibliothek ist leer",
                emptyLibrarySubtitle = "Tippen Sie auf (+), um Ihre erste PDF zu öffnen.",
                noSearchResultsTitle = "Keine Ergebnisse gefunden",
                noSearchResultsSubtitle = "Überprüfen Sie den Dateinamen und versuchen Sie es erneut.",
                totalFiles = "Gesamte Dateien",
                favoriteFiles = "Favoriten",
                openedFiles = "Geöffnete Dateien",
                readingHours = "Lesezeit",
                missingFiles = "Fehlende Dateien",
                totalPdfs = "PDFs",
                totalFolders = "Ordner",
                documentSize = "Dokumentengröße",
                libraryOverviewSubtitle = "Übersicht über Dateien und Leseaktivitäten in Ihrer Bibliothek",
                sampleFiles = "Beispieldateien",
                pdfFiles = "PDF-Dateien",
                folders = "Ordner",
                sampleDocumentTitle = "Beispieldokument (14 Seiten)",
                importedDocuments = "Importierte Dokumente",
                unknown = "Unbekannt",
                fileCountFormat = { count -> "$count PDF${if (count != 1) "s" else ""}" },
                toolsTitle = "Erweiterte PDF-Werkzeuge",
                toolsSubtitle = "Intelligente Tools zum Bearbeiten und Verwalten von PDFs",
                cameraOcrTitle = "Kamera-OCR-Scanner",
                cameraOcrDesc = "Dokumente erfassen und Text sofort extrahieren",
                cloudOcrTitle = "PDF zu Text (OCR)",
                cloudOcrDesc = "Gescannte Seiten in bearbeitbaren Text umwandeln",
                mergePdfTitle = "PDFs zusammenfügen",
                mergePdfDesc = "Mehrere PDF-Dateien in eine einzige zusammenführen",
                splitPdfTitle = "PDF teilen",
                splitPdfDesc = "Bestimmte Seiten in eine neue PDF-Datei extrahieren",
                compressPdfTitle = "PDF komprimieren",
                compressPdfDesc = "Dateigröße für einfaches Teilen reduzieren",
                rotatePdfTitle = "Seiten drehen",
                rotatePdfDesc = "Ausgewählte oder alle Seiten drehen",
                reorderPdfTitle = "Seiten neu ordnen",
                reorderPdfDesc = "PDF-Seiten per Drag-and-Drop neu anordnen",
                deletePdfTitle = "Seiten löschen",
                deletePdfDesc = "Unerwünschte Seiten aus PDF entfernen",
                appearanceSection = "ERSCHEINUNGSBILD",
                appThemeTitle = "App-Design",
                appLanguageTitle = "App- & Erkennungssprache",
                showToolsTabTitle = "Werkzeuge-Tab anzeigen",
                showToolsTabSubtitle = "Werkzeuge-Tab in der untere Leiste ein- oder ausblenden",
                readerDisplaySection = "LESER & ANZEIGE",
                scrollDirectionTitle = "Scroll-Richtung",
                defaultZoomTitle = "Standard-Zoomstufe",
                doubleTapZoomTitle = "Doppeltipp-Zoom",
                readingThemeTitle = "Lese-Hintergrunddesign",
                sortSubtitle = "Wählen Sie, wie Ihre PDF-Dateien organisiert und angezeigt werden sollen",
                sortAlphabetical = "Alphabetisch",
                sortAlphaAsc = "A -> Z  ↑",
                sortAlphaDesc = "Z -> A  ↓",
                sortFileSizeLabel = "Dateigröße",
                sortSizeAsc = "Kleinste zuerst  ↑",
                sortSizeDesc = "Größte zuerst  ↓",
                sortDateAddedLabel = "Hinzugefügt am",
                sortDateAsc = "Älteste zuerst  ↑",
                sortDateDesc = "Neueste zuerst  ↓",
                quickActions = "Schnellaktionen",
                addToFav = "Zu Favoriten hinzufügen",
                removeFromFav = "Aus Favoriten entfernen",
                addToFavDesc = "In Ihren Favoriten speichern für schnellen Zugriff",
                removeFromFavDesc = "Aus Ihrer Favoritenliste entfernen",
                selectFile = "Datei auswählen",
                selectFileDesc = "Mehrfachauswahlmodus für diese Datei aktivieren",
                shareFile = "Datei teilen",
                shareFileDesc = "Diese PDF an andere Anwendungen senden",
                renameFile = "Umbenennen",
                renameFileDesc = "Dokumententitel oder Dateinamen ändern",
                fileInfo = "Datei-Info",
                fileInfoDesc = "Eigenschaften und Metadaten anzeigen",
                deleteFile = "Datei löschen",
                deleteFileDesc = "Datei vom Gerät oder aus der Bibliothek entfernen",
                openDocument = "Dokument öffnen",
                share = "Teilen",
                copyPath = "Pfad kopieren",
                pathCopied = "Dateipfad in die Zwischenablage kopiert",
                fullPath = "Vollständiger Pfad:",
                folderName = "Ordnername",
                storageLocationSection = "Speicherort",
                pdfVersion = "PDF-Version",
                encryption = "Sicherheit",
                encrypted = "Passwortgeschützt",
                notEncrypted = "Ungeschützt",
                authorSection = "Autor & Dokumentdetails",
                authorLabel = "Autor / Verfasser",
                documentTitleLabel = "Dokumenttitel",
                subjectLabel = "Thema",
                keywordsLabel = "Schlüsselwörter",
                datesSection = "Datum & Uhrzeit",
                creationDate = "Erstellungsdatum",
                modificationDate = "Zuletzt geändert",
                creatorAppSection = "Ersteller & Engine",
                creatorLabel = "Erstellungsprogramm",
                producerLabel = "PDF-Producer",
                extractingMetadata = "Dokumenteigenschaften werden extrahiert...",
                pagesTab = "Seiten",
                viewTab = "Ansicht",
                zoomTab = "Zoom",
                themesTab = "Designs",
                bookmarkTab = "Lesezeichen",
                moreTab = "Werkzeuge",
                searchInPdf = "In PDF suchen",
                jumpToPage = "Gehe zu Seite",
                tableOfContents = "Inhaltsverzeichnis",
                readAloud = "Vorlesen (TTS)",
                autoScroll = "Autom. Scrollen",
                cropPages = "Seiten zuschneiden",
                ocrExtract = "Text extrahieren (OCR)",
                notesHighlights = "Notizen & Hervorhebungen",
                exportImage = "Als Bild exportieren",
                printDocument = "Dokument drucken",
                fitWidth = "An Breite anpassen",
                fitPage = "An Seite anpassen",
                actualSize = "100% Originalgröße",
                themeLight = "Heller Hintergrund",
                themeDark = "Dunkelmodus",
                themeSepia = "Warmes Sepia",
                themeAmoled = "OLED Tiefschwarz",
                goButton = "Los",
                closeButton = "Schließen",
                cancelButton = "Abbrechen",
                saveButton = "Speichern",
                confirmButton = "Bestätigen",
                cameraPermissionTitle = "Kamerazugriff erforderlich",
                cameraPermissionDesc = "Kamerazugriff wird benötigt, um Dokumente zu scannen.",
                grantPermission = "Kamerazugriff erlauben",
                copyText = "Text kopieren",
                singleMode = "Einzeln",
                batchMode = "Stapel",
                importFiles = "Dateien importieren",
                importImages = "Bilder importieren",
                exitAppTitle = "FinalPDF beenden?",
                exitAppSubtitle = "Möchten Sie die Anwendung wirklich beenden?",                exitAppConfirm = "Exit App",
                selectFromLibrary = "Choose from Local Library",
                internalStorage = "Internal Storage",
                processSuccess = "Process completed successfully!",
                fileSavedInFinalPDF = "File saved successfully in FinalPDF folder",
                autoSystem = "Auto (System)",
                verticalScroll = "Vertical Scroll",
                horizontalScroll = "Horizontal Scroll",
                portraitMode = "Portrait",
                landscapeMode = "Landscape",
                useSystemBrightness = "Systemhelligkeit verwenden",
                lockPdfTitle = "PDF schützen & sperren",
                lockPdfDesc = "Dokument mit Passworteingabe schützen",
                unlockPdfTitle = "PDF entsperren",
                unlockPdfDesc = "Passwortschutz von PDF entfernen",
                confirm = "Bestätigen",
                noPdfSelected = "Keine PDF-Datei ausgewählt",
                noPdfFound = "Keine PDF-Dateien gefunden"
            )
            "es" -> AppStrings(
                home = "Inicio",
                documents = "Documentos",
                tools = "Herramientas",
                settings = "Ajustes",
                goodMorning = "¡Buenos días!",
                goodEvening = "¡Buenas noches!",
                welcomeMessage = "Bienvenido a FinalPDF",
                statsTitle = "Estadísticas de biblioteca",
                sortTitle = "Ordenar archivos",
                searchPlaceholder = "Buscar archivos PDF...",
                recent = "Recientes",
                favorites = "Favoritos",
                allDocs = "Todos",
                emptyLibraryTitle = "Tu biblioteca está vacía",
                emptyLibrarySubtitle = "Presiona (+) para abrir y leer tu primer archivo PDF.",
                noSearchResultsTitle = "Sin resultados coincidentes",
                noSearchResultsSubtitle = "Revisa el nombre del archivo e intenta nuevamente.",
                totalFiles = "Total Archivos",
                favoriteFiles = "Favoritos",
                openedFiles = "Archivos Abiertos",
                readingHours = "Tiempo de Lectura",
                missingFiles = "Archivos faltantes",
                totalPdfs = "PDFs",
                totalFolders = "Carpetas",
                documentSize = "Tamaño de documentos",
                libraryOverviewSubtitle = "Resumen de archivos y actividad de lectura",
                sampleFiles = "Archivos de muestra",
                pdfFiles = "Archivos PDF",
                folders = "Carpetas",
                sampleDocumentTitle = "Documento de muestra (14 páginas)",
                importedDocuments = "Documentos importados",
                unknown = "Desconocido",
                fileCountFormat = { count -> "$count PDF${if (count != 1) "s" else ""}" },
                toolsTitle = "Herramientas PDF Avanzadas",
                toolsSubtitle = "Herramientas inteligentes para editar y gestionar tus PDF",
                cameraOcrTitle = "Escáner OCR de Cámara",
                cameraOcrDesc = "Escanea documentos y extrae texto al instante",
                cloudOcrTitle = "PDF a Texto (OCR)",
                cloudOcrDesc = "Convierte páginas escaneadas en texto editable",
                mergePdfTitle = "Combinar archivos PDF",
                mergePdfDesc = "Une múltiples archivos PDF en uno solo",
                splitPdfTitle = "Dividir archivo PDF",
                splitPdfDesc = "Extrae páginas específicas a un nuevo PDF",
                compressPdfTitle = "Comprimir PDF",
                compressPdfDesc = "Reduce el tamaño para compartir fácilmente",
                rotatePdfTitle = "Rotar páginas",
                rotatePdfDesc = "Gira páginas seleccionadas o todas",
                reorderPdfTitle = "Reordenar páginas",
                reorderPdfDesc = "Arrastra y reorganiza las páginas del PDF",
                deletePdfTitle = "Eliminar páginas",
                deletePdfDesc = "Elimina páginas no deseadas del PDF",
                appearanceSection = "APARIENCIA",
                appThemeTitle = "Tema de la aplicación",
                appLanguageTitle = "Idioma de la aplicación",
                showToolsTabTitle = "Mostrar pestaña Herramientas",
                showToolsTabSubtitle = "Mostrar u ocultar la pestaña Herramientas en la barra inferior",
                readerDisplaySection = "LECTURA Y PANTALLA",
                scrollDirectionTitle = "Dirección de desplazamiento",
                defaultZoomTitle = "Nivel de zoom predeterminado",
                doubleTapZoomTitle = "Zoom por doble toque",
                readingThemeTitle = "Tema de fondo de lectura",
                sortSubtitle = "Elige cómo organizar y ver tus archivos PDF",
                sortAlphabetical = "Alfabético",
                sortAlphaAsc = "A -> Z  ↑",
                sortAlphaDesc = "Z -> A  ↓",
                sortFileSizeLabel = "Tamaño del archivo",
                sortSizeAsc = "Más pequeño primero  ↑",
                sortSizeDesc = "Más grande primero  ↓",
                sortDateAddedLabel = "Fecha de adición",
                sortDateAsc = "Más antiguo primero  ↑",
                sortDateDesc = "Más reciente primero  ↓",
                quickActions = "Acciones Rápidas",
                addToFav = "Añadir a Favoritos",
                removeFromFav = "Quitar de Favoritos",
                addToFavDesc = "Guarda en tus favoritos para un acceso rápido",
                removeFromFavDesc = "Elimina de tu lista de archivos favoritos",
                selectFile = "Seleccionar archivo",
                selectFileDesc = "Activar modo de selección múltiple para este archivo",
                shareFile = "Compartir archivo",
                shareFileDesc = "Enviar este PDF a otras aplicaciones",
                renameFile = "Renombrar",
                renameFileDesc = "Cambiar el título del documento o el nombre",
                fileInfo = "Info del archivo",
                fileInfoDesc = "Ver propiedades y metadatos detallados",
                deleteFile = "Eliminar archivo",
                deleteFileDesc = "Eliminar archivo del dispositivo o biblioteca",
                openDocument = "Abrir documento",
                share = "Compartir",
                copyPath = "Copiar ruta",
                pathCopied = "Ruta copiada al portapapeles",
                fullPath = "Ruta completa:",
                folderName = "Nombre de carpeta",
                storageLocationSection = "Ubicación y almacenamiento",
                pdfVersion = "Versión de PDF",
                encryption = "Seguridad",
                encrypted = "Protegido con contraseña",
                notEncrypted = "Sin protección",
                authorSection = "Autor y detalles del documento",
                authorLabel = "Autor / Escritor",
                documentTitleLabel = "Título del documento",
                subjectLabel = "Asunto",
                keywordsLabel = "Palabras clave",
                datesSection = "Fechas y hora",
                creationDate = "Fecha de creación",
                modificationDate = "Última modificación",
                creatorAppSection = "Creador y motor",
                creatorLabel = "Programa creador",
                producerLabel = "Productor PDF",
                extractingMetadata = "Extrayendo propiedades del documento...",
                pagesTab = "Páginas",
                viewTab = "Vista",
                zoomTab = "Zoom",
                themesTab = "Temas",
                bookmarkTab = "Marcador",
                moreTab = "Herramientas",
                searchInPdf = "Buscar en el PDF",
                jumpToPage = "Ir a la página",
                tableOfContents = "Tabla de contenidos",
                readAloud = "Lectura en voz alta (TTS)",
                autoScroll = "Desplazamiento auto",
                cropPages = "Recortar páginas",
                ocrExtract = "Extraer texto (OCR)",
                notesHighlights = "Notas y destacados",
                exportImage = "Exportar como imagen",
                printDocument = "Imprimir documento",
                fitWidth = "Ajustar al ancho",
                fitPage = "Ajustar a la página",
                actualSize = "Tamaño real 100%",
                themeLight = "Fondo Claro",
                themeDark = "Modo Oscuro",
                themeSepia = "Sepia Cálido",
                themeAmoled = "Negro OLED",
                goButton = "Ir",
                closeButton = "Cerrar",
                cancelButton = "Cancelar",
                saveButton = "Guardar",
                confirmButton = "Confirmar",
                cameraPermissionTitle = "Permiso de cámara requerido",
                cameraPermissionDesc = "Se requiere acceso a la cámara para escanear documentos.",
                grantPermission = "Conceder permiso",
                copyText = "Copiar texto",
                singleMode = "Individual",
                batchMode = "Lote",
                importFiles = "Importar archivos",
                importImages = "Importar imágenes",
                exitAppTitle = "¿Salir de FinalPDF?",
                exitAppSubtitle = "¿Estás seguro de que deseas salir de la aplicación?",                exitAppConfirm = "Exit App",
                selectFromLibrary = "Choose from Local Library",
                internalStorage = "Internal Storage",
                processSuccess = "Process completed successfully!",
                fileSavedInFinalPDF = "File saved successfully in FinalPDF folder",
                autoSystem = "Auto (System)",
                verticalScroll = "Vertical Scroll",
                horizontalScroll = "Horizontal Scroll",
                portraitMode = "Portrait",
                landscapeMode = "Landscape",
                useSystemBrightness = "Usar brillo del sistema",
                lockPdfTitle = "Proteger y bloquear PDF",
                lockPdfDesc = "Proteger el documento con contraseña",
                unlockPdfTitle = "Desbloquear PDF",
                unlockPdfDesc = "Eliminar la contraseña del PDF",
                confirm = "Confirmar",
                noPdfSelected = "Ningún archivo PDF seleccionado",
                noPdfFound = "No se encontraron archivos PDF"
            )
            "tr" -> AppStrings(
                home = "Ana Sayfa",
                documents = "Belgeler",
                tools = "Araçlar",
                settings = "Ayarlar",
                goodMorning = "Günaydın!",
                goodEvening = "İyi akşamlar!",
                welcomeMessage = "FinalPDF'e Hoş Geldiniz",
                statsTitle = "Kütüphane İstatistikleri",
                sortTitle = "Dosyaları Sırala",
                searchPlaceholder = "PDF dosyalarında ara...",
                recent = "Son",
                favorites = "Favoriler",
                allDocs = "Tüm Belge.",
                emptyLibraryTitle = "Kütüphaneniz şu an boş",
                emptyLibrarySubtitle = "İlk PDF dosyanızı açmak için (+) düğmesine dokunun.",
                noSearchResultsTitle = "Arama sonucu bulunamadı",
                noSearchResultsSubtitle = "Dosya adını kontrol edip tekrar deneyin.",
                totalFiles = "Toplam Dosya",
                favoriteFiles = "Favoriler",
                openedFiles = "Açılan Dosyalar",
                readingHours = "Okuma Süresi",
                missingFiles = "Eksik Dosyalar",
                totalPdfs = "PDF'ler",
                totalFolders = "Klasörler",
                documentSize = "Belge Boyutu",
                libraryOverviewSubtitle = "Kütüphanenizdeki dosyalar ve okuma özeti",
                sampleFiles = "Örnek Dosyalar",
                pdfFiles = "PDF Dosyaları",
                folders = "Klasörler",
                sampleDocumentTitle = "Örnek Belge (14 sayfa)",
                importedDocuments = "İçe Aktarılan Belgeler",
                unknown = "Bilinmiyor",
                fileCountFormat = { count -> "$count PDF" },
                toolsTitle = "Gelişmiş PDF Araçları",
                toolsSubtitle = "PDF'lerinizi düzenlemek ve yönetmek için akıllı araçlar",
                cameraOcrTitle = "Kamera OCR Tarayıcı",
                cameraOcrDesc = "Belgeleri tara ve metni anında çıkar",
                cloudOcrTitle = "PDF'den Metne (OCR)",
                cloudOcrDesc = "Taranmış PDF sayfalarını düzenlenebilir metne dönüştür",
                mergePdfTitle = "PDF Birleştir",
                mergePdfDesc = "Birden fazla PDF dosyasını tek bir dosyada birleştir",
                splitPdfTitle = "PDF Böl",
                splitPdfDesc = "Belirli sayfaları yeni bir PDF'e çıkar",
                compressPdfTitle = "PDF Sıkıştır",
                compressPdfDesc = "Kolay paylaşım için dosya boyutunu küçült",
                rotatePdfTitle = "Sayfaları Döndür",
                rotatePdfDesc = "Seçilen veya tüm sayfaları döndür",
                reorderPdfTitle = "Sayfaları Sırala",
                reorderPdfDesc = "Sayfaları sürükleyerek yeniden sırala",
                deletePdfTitle = "Sayfaları Sil",
                deletePdfDesc = "İstenmeyen sayfaları PDF'den kaldır",
                appearanceSection = "GÖRÜNÜM",
                appThemeTitle = "Uygulama Teması",
                appLanguageTitle = "Uygulama Dili",
                showToolsTabTitle = "Araçlar Sekmesini Göster",
                showToolsTabSubtitle = "Alt çubukta araçlar sekmesini göster veya gizle",
                readerDisplaySection = "OKUYUCU VE EKRAN",
                scrollDirectionTitle = "Kaydırma Yönü",
                defaultZoomTitle = "Varsayılan Yakınlaştırma",
                doubleTapZoomTitle = "Çift Dokunma Yakınlaştırma",
                readingThemeTitle = "Okuma Arka Plan Teması",
                sortSubtitle = "PDF dosyalarınızı nasıl düzenleyeceğinizi seçin",
                sortAlphabetical = "Alfabetik",
                sortAlphaAsc = "A -> Z  ↑",
                sortAlphaDesc = "Z -> A  ↓",
                sortFileSizeLabel = "Dosya Boyutu",
                sortSizeAsc = "Önce en küçük  ↑",
                sortSizeDesc = "Önce en büyük  ↓",
                sortDateAddedLabel = "Ekleme Tarihi",
                sortDateAsc = "Önce en eski  ↑",
                sortDateDesc = "Önce en yeni  ↓",
                quickActions = "Hızlı Eylemler",
                addToFav = "Favorilere Ekle",
                removeFromFav = "Favorilerden Çıkar",
                addToFavDesc = "Hızlı erişim için favorilerinize kaydedin",
                removeFromFavDesc = "Favori dosyalar listenizden kaldırın",
                selectFile = "Dosyayı Seç",
                selectFileDesc = "Bu dosya için çoklu seçim moduna geçin",
                shareFile = "Dosyayı Paylaş",
                shareFileDesc = "Bu PDF'i diğer uygulamalara gönderin",
                renameFile = "Yeniden Adlandır",
                renameFileDesc = "Belge başlığını veya dosya adını değiştirin",
                fileInfo = "Dosya Bilgisi",
                fileInfoDesc = "Ayrıntılı özellikleri ve üst verileri görüntüleyin",
                deleteFile = "Dosyayı Sil",
                deleteFileDesc = "Dosyayı cihazdan veya kütüphaneden kaldırın",
                openDocument = "Belgeyi Aç",
                share = "Paylaş",
                copyPath = "Yolu Kopyala",
                pathCopied = "Dosya yolu panoya kopyalandı",
                fullPath = "Tam Yol:",
                folderName = "Klasör Adı",
                storageLocationSection = "Konum ve Depolama",
                pdfVersion = "PDF Sürümü",
                encryption = "Güvenlik",
                encrypted = "Parola Korumalı",
                notEncrypted = "Korumasız",
                authorSection = "Yazar ve Belge Detayları",
                authorLabel = "Yazar",
                documentTitleLabel = "Belge Başlığı",
                subjectLabel = "Konu",
                keywordsLabel = "Anahtar Kelimeler",
                datesSection = "Tarihler ve Zaman",
                creationDate = "Oluşturma Tarihi",
                modificationDate = "Son Değiştirme",
                creatorAppSection = "Oluşturan Program",
                creatorLabel = "Oluşturan Araç",
                producerLabel = "PDF Üreticisi",
                extractingMetadata = "Belge özellikleri ayıklanıyor...",
                pagesTab = "Sayfalar",
                viewTab = "Görünüm",
                zoomTab = "Yakınlaştır",
                themesTab = "Temalar",
                bookmarkTab = "Yer İmi",
                moreTab = "Araçlar",
                searchInPdf = "PDF'de Ara",
                jumpToPage = "Sayfaya Git",
                tableOfContents = "İçindekiler",
                readAloud = "Sesli Oku (TTS)",
                autoScroll = "Otomatik Kaydır",
                cropPages = "Sayfaları Kırp",
                ocrExtract = "Metin Çıkar (OCR)",
                notesHighlights = "Notlar ve Vurgular",
                exportImage = "Görüntü Olarak Dışa Aktar",
                printDocument = "Belgeyi Yazdır",
                fitWidth = "Genişliğe Sığdır",
                fitPage = "Sayfaya Sığdır",
                actualSize = "%100 Gerçek Boyut",
                themeLight = "Açık Arka Plan",
                themeDark = "Karanlık Mod",
                themeSepia = "Sıcak Sepya",
                themeAmoled = "OLED Derin Siyah",
                goButton = "Git",
                closeButton = "Kapat",
                cancelButton = "İptal",
                saveButton = "Kaydet",
                confirmButton = "Onayla",
                cameraPermissionTitle = "Kamera İzni Gerekli",
                cameraPermissionDesc = "Belgeleri taramak için kamera erişimi gereklidir.",
                grantPermission = "Kamera İznini Ver",
                copyText = "Metni Kopyala",
                singleMode = "Tekli",
                batchMode = "Toplu",
                importFiles = "Dosya İçe Aktar",
                importImages = "Resim İçe Aktar",
                exitAppTitle = "FinalPDF'ten Çıkılsın mı?",
                exitAppSubtitle = "Uygulamadan çıkmak istediğinizden emin misiniz?",                exitAppConfirm = "Exit App",
                selectFromLibrary = "Choose from Local Library",
                internalStorage = "Internal Storage",
                processSuccess = "Process completed successfully!",
                fileSavedInFinalPDF = "File saved successfully in FinalPDF folder",
                autoSystem = "Auto (System)",
                verticalScroll = "Vertical Scroll",
                horizontalScroll = "Horizontal Scroll",
                portraitMode = "Portrait",
                landscapeMode = "Landscape",
                useSystemBrightness = "Sistem Parlaklığını Kullan",
                lockPdfTitle = "PDF Kilitle ve Koru",
                lockPdfDesc = "Belgeyi şifre ile koruyun",
                unlockPdfTitle = "PDF Kilidini Aç",
                unlockPdfDesc = "Şifreli PDF korumasını kaldırın",
                confirm = "Onayla",
                noPdfSelected = "PDF dosyası seçilmedi",
                noPdfFound = "PDF dosyası bulunamadı"
            )
            "ru" -> AppStrings(
                home = "Главная",
                documents = "Документы",
                tools = "Инструменты",
                settings = "Настройки",
                goodMorning = "Доброе утро!",
                goodEvening = "Добрый вечер!",
                welcomeMessage = "Добро пожаловать в FinalPDF",
                statsTitle = "Статистика библиотеки",
                sortTitle = "Сортировка файлов",
                searchPlaceholder = "Поиск PDF файлов...",
                recent = "Недавние",
                favorites = "Избранное",
                allDocs = "Все док.",
                emptyLibraryTitle = "Ваша библиотека пуста",
                emptyLibrarySubtitle = "Нажмите (+), чтобы открыть свой первый PDF файл.",
                noSearchResultsTitle = "Результатов не найдено",
                noSearchResultsSubtitle = "Проверьте название файла и повторите поиск.",
                totalFiles = "Всего файлов",
                favoriteFiles = "Избранное",
                openedFiles = "Открытые файлы",
                readingHours = "Время чтения",
                missingFiles = "Удаленные файлы",
                totalPdfs = "PDF-файлы",
                totalFolders = "Папки",
                documentSize = "Размер документов",
                libraryOverviewSubtitle = "Обзор файлов и активности чтения в вашей библиотеке",
                sampleFiles = "Образцы файлов",
                pdfFiles = "Файлы PDF",
                folders = "Папки",
                sampleDocumentTitle = "Образец документа (14 страниц)",
                importedDocuments = "Импортированные документы",
                unknown = "Неизвестно",
                fileCountFormat = { count -> "$count PDF" },
                toolsTitle = "Расширенные инструменты PDF",
                toolsSubtitle = "Умные инструменты для редактирования и управления PDF",
                cameraOcrTitle = "Камера OCR Сканер",
                cameraOcrDesc = "Сканируйте документы и извлекайте текст мгновенно",
                cloudOcrTitle = "PDF в текст (OCR)",
                cloudOcrDesc = "Конвертируйте сканированные страницы в текст",
                mergePdfTitle = "Объединить PDF файлы",
                mergePdfDesc = "Объединяйте несколько PDF в один файл",
                splitPdfTitle = "Разделить PDF файл",
                splitPdfDesc = "Извлекайте нужные страницы в новый PDF",
                compressPdfTitle = "Сжать PDF",
                compressPdfDesc = "Уменьшайте размер файла для удобной отправки",
                rotatePdfTitle = "Повернуть страницы",
                rotatePdfDesc = "Поворачивайте выбранные или все страницы",
                reorderPdfTitle = "Переставить страницы",
                reorderPdfDesc = "Перетаскивайте страницы для изменения порядка",
                deletePdfTitle = "Удалить страницы",
                deletePdfDesc = "Удаляйте ненужные страницы из PDF",
                appearanceSection = "ВНЕШНИЙ ВИД",
                appThemeTitle = "Тема приложения",
                appLanguageTitle = "Язык приложения",
                showToolsTabTitle = "Показывать вкладку инструментов",
                showToolsTabSubtitle = "Показать или скрыть вкладку инструментов в нижней панели",
                readerDisplaySection = "ЧТЕНИЕ И ЭКРАН",
                scrollDirectionTitle = "Направление прокрутки",
                defaultZoomTitle = "Масштаб по умолчанию",
                doubleTapZoomTitle = "Масштаб по двойному нажатию",
                readingThemeTitle = "Фон страницы чтения",
                sortSubtitle = "Выберите способ организации и просмотра ваших PDF-файлов",
                sortAlphabetical = "По алфавиту",
                sortAlphaAsc = "А -> Я  ↑",
                sortAlphaDesc = "Я -> А  ↓",
                sortFileSizeLabel = "Размер файла",
                sortSizeAsc = "Сначала меньшие  ↑",
                sortSizeDesc = "Сначала большие  ↓",
                sortDateAddedLabel = "Дата добавления",
                sortDateAsc = "Сначала старые  ↑",
                sortDateDesc = "Сначала новые  ↓",
                quickActions = "Быстрые действия",
                addToFav = "Добавить в избранное",
                removeFromFav = "Удалить из избранного",
                addToFavDesc = "Сохранить в избранное для быстрого доступа",
                removeFromFavDesc = "Удалить из списка избранных файлов",
                selectFile = "Выбрать файл",
                selectFileDesc = "Включить режим выбора нескольких файлов",
                shareFile = "Поделиться файлом",
                shareFileDesc = "Отправить PDF в другие приложения",
                renameFile = "Переименовать",
                renameFileDesc = "Изменить название документа или файла",
                fileInfo = "О файле",
                fileInfoDesc = "Просмотр свойств и метаданных",
                deleteFile = "Удалить файл",
                deleteFileDesc = "Удалить файл с устройства или из библиотеки",
                openDocument = "Открыть документ",
                share = "Поделиться",
                copyPath = "Копировать путь",
                pathCopied = "Путь к файлу скопирован в буфер обмена",
                fullPath = "Полный путь:",
                folderName = "Название папки",
                storageLocationSection = "Расположение и память",
                pdfVersion = "Версия PDF",
                encryption = "Защита",
                encrypted = "Защищен паролем",
                notEncrypted = "Без защиты",
                authorSection = "Автор и детали документа",
                authorLabel = "Автор / Писатель",
                documentTitleLabel = "Название документа",
                subjectLabel = "Тема",
                keywordsLabel = "Ключевые слова",
                datesSection = "Даты и время",
                creationDate = "Дата создания",
                modificationDate = "Дата изменения",
                creatorAppSection = "Создатель и движок",
                creatorLabel = "Программа создания",
                producerLabel = "Производитель PDF",
                extractingMetadata = "Извлечение свойств документа...",
                pagesTab = "Страницы",
                viewTab = "Вид",
                zoomTab = "Масштаб",
                themesTab = "Темы",
                bookmarkTab = "Закладка",
                moreTab = "Инструменты",
                searchInPdf = "Поиск в PDF",
                jumpToPage = "Перейти к странице",
                tableOfContents = "Содержание",
                readAloud = "Чтение вслух (TTS)",
                autoScroll = "Автопрокрутка",
                cropPages = "Обрезать страницы",
                ocrExtract = "Распознать текст (OCR)",
                notesHighlights = "Заметки и выделения",
                exportImage = "Экспорт в изображение",
                printDocument = "Печать документа",
                fitWidth = "По ширине",
                fitPage = "По странице",
                actualSize = "100% Реальный размер",
                themeLight = "Светлый фон",
                themeDark = "Тёмная тема",
                themeSepia = "Тёплая сепия",
                themeAmoled = "OLED Глубокий чёрный",
                goButton = "Перейти",
                closeButton = "Закрыть",
                cancelButton = "Отмена",
                saveButton = "Сохранить",
                confirmButton = "Подтвердить",
                cameraPermissionTitle = "Требуется разрешение камеры",
                cameraPermissionDesc = "Доступ к камере необходим для сканирования документов.",
                grantPermission = "Предоставить доступ",
                copyText = "Копировать текст",
                singleMode = "Одиночный",
                batchMode = "Пакетный",
                importFiles = "Импорт файлов",
                importImages = "Импорт фото",
                exitAppTitle = "Выйти из FinalPDF?",
                exitAppSubtitle = "Вы уверены, что хотите выйти из приложения?",                exitAppConfirm = "Exit App",
                selectFromLibrary = "Choose from Local Library",
                internalStorage = "Internal Storage",
                processSuccess = "Process completed successfully!",
                fileSavedInFinalPDF = "File saved successfully in FinalPDF folder",
                autoSystem = "Auto (System)",
                verticalScroll = "Vertical Scroll",
                horizontalScroll = "Horizontal Scroll",
                portraitMode = "Portrait",
                landscapeMode = "Landscape",
                useSystemBrightness = "Использовать системную яркость",
                lockPdfTitle = "Защита и блокировка PDF",
                lockPdfDesc = "Защитить документ паролем",
                unlockPdfTitle = "Снять защиту PDF",
                unlockPdfDesc = "Удалить пароль с зашифрованного PDF",
                confirm = "Подтвердить",
                noPdfSelected = "Файл PDF не выбран",
                noPdfFound = "Файлы PDF не найдены"
            )
            "zh" -> AppStrings(
                home = "首页",
                documents = "文档",
                tools = "工具",
                settings = "设置",
                goodMorning = "早上好！",
                goodEvening = "晚上好！",
                welcomeMessage = "欢迎使用 FinalPDF",
                statsTitle = "图书库统计",
                sortTitle = "文件排序",
                searchPlaceholder = "搜索 PDF 文件...",
                recent = "最近",
                favorites = "收藏",
                allDocs = "所有文档",
                emptyLibraryTitle = "您的图书库为空",
                emptyLibrarySubtitle = "点击 (+) 打开并阅读您的首个 PDF 文件。",
                noSearchResultsTitle = "未找到匹配结果",
                noSearchResultsSubtitle = "请检查文件名后重试。",
                totalFiles = "文件总数",
                favoriteFiles = "收藏文件",
                openedFiles = "已打开文件",
                readingHours = "阅读时长",
                missingFiles = "缺失文件",
                totalPdfs = "PDF 文件",
                totalFolders = "文件夹",
                documentSize = "文档总容量",
                libraryOverviewSubtitle = "图书库文件及阅读活动概览",
                sampleFiles = "示例文件",
                pdfFiles = "PDF 文件",
                folders = "文件夹",
                sampleDocumentTitle = "示例文档 (14 页)",
                importedDocuments = "导入的文档",
                unknown = "未知",
                fileCountFormat = { count -> "$count 个 PDF" },
                toolsTitle = "高级 PDF 工具",
                toolsSubtitle = "用于编辑、转换和管理 PDF 的智能工具",
                cameraOcrTitle = "相机 OCR 扫描",
                cameraOcrDesc = "扫描文档并立即提取文本",
                cloudOcrTitle = "PDF 转文本 (OCR)",
                cloudOcrDesc = "将扫描页面转换为可编辑文本",
                mergePdfTitle = "合并 PDF 文件",
                mergePdfDesc = "将多个 PDF 文件合并为一个",
                splitPdfTitle = "拆分 PDF 文件",
                splitPdfDesc = "将指定页面提取为新的 PDF",
                compressPdfTitle = "压缩 PDF",
                compressPdfDesc = "减小文件体积以便于分享",
                rotatePdfTitle = "旋转页面",
                rotatePdfDesc = "旋转选定页面或全部页面",
                reorderPdfTitle = "重排页面",
                reorderPdfDesc = "拖拽调整 PDF 页面顺序",
                deletePdfTitle = "删除页面",
                deletePdfDesc = "从 PDF 中删除不需要的页面",
                appearanceSection = "外观",
                appThemeTitle = "应用主题",
                appLanguageTitle = "应用与识别语言",
                showToolsTabTitle = "显示工具标签页",
                showToolsTabSubtitle = "在底部栏中显示或隐藏工具标签页",
                readerDisplaySection = "阅读与显示",
                scrollDirectionTitle = "滚动方向",
                defaultZoomTitle = "默认缩放级别",
                doubleTapZoomTitle = "双击缩放",
                readingThemeTitle = "阅读背景主题",
                sortSubtitle = "选择如何组织和查看您的 PDF 文件",
                sortAlphabetical = "按字母顺序",
                sortAlphaAsc = "A -> Z  ↑",
                sortAlphaDesc = "Z -> A  ↓",
                sortFileSizeLabel = "文件大小",
                sortSizeAsc = "最小优先  ↑",
                sortSizeDesc = "最大优先  ↓",
                sortDateAddedLabel = "添加日期",
                sortDateAsc = "最早优先  ↑",
                sortDateDesc = "最新优先  ↓",
                quickActions = "快捷操作",
                addToFav = "添加至收藏",
                removeFromFav = "取消收藏",
                addToFavDesc = "保存到收藏以便快速访问",
                removeFromFavDesc = "从收藏列表中移除",
                selectFile = "选择文件",
                selectFileDesc = "开启多选模式",
                shareFile = "分享文件",
                shareFileDesc = "将此 PDF 发送至其他应用",
                renameFile = "重命名",
                renameFileDesc = "修改文档标题或文件名",
                fileInfo = "文件信息",
                fileInfoDesc = "查看详细属性和元数据",
                deleteFile = "删除文件",
                deleteFileDesc = "从设备或库中删除文件",
                openDocument = "打开文档",
                share = "分享",
                copyPath = "复制路径",
                pathCopied = "文件路径已复制到剪贴板",
                fullPath = "完整路径：",
                folderName = "文件夹名称",
                storageLocationSection = "位置与存储",
                pdfVersion = "PDF 版本",
                encryption = "安全保护",
                encrypted = "密码保护",
                notEncrypted = "未保护",
                authorSection = "作者与文档详情",
                authorLabel = "作者",
                documentTitleLabel = "文档标题",
                subjectLabel = "主题",
                keywordsLabel = "关键词",
                datesSection = "日期与时间",
                creationDate = "创建日期",
                modificationDate = "修改时间",
                creatorAppSection = "创建工具与引擎",
                creatorLabel = "创建软件",
                producerLabel = "PDF 生产商",
                extractingMetadata = "正在提取文档属性元数据...",
                pagesTab = "页面",
                viewTab = "视图",
                zoomTab = "缩放",
                themesTab = "主题",
                bookmarkTab = "书签",
                moreTab = "工具",
                searchInPdf = "在 PDF 中搜索",
                jumpToPage = "跳转至页面",
                tableOfContents = "目录",
                readAloud = "朗读 (TTS)",
                autoScroll = "自动滚动",
                cropPages = "裁剪页面",
                ocrExtract = "提取文本 (OCR)",
                notesHighlights = "笔记与高亮",
                exportImage = "导出为图片",
                printDocument = "打印文档",
                fitWidth = "适应宽度",
                fitPage = "适应页面",
                actualSize = "100% 实际大小",
                themeLight = "亮色背景",
                themeDark = "暗黑模式",
                themeSepia = "暖色棕褐",
                themeAmoled = "OLED 纯黑",
                goButton = "前往",
                closeButton = "关闭",
                cancelButton = "取消",
                saveButton = "保存",
                confirmButton = "确认",
                cameraPermissionTitle = "需要相机权限",
                cameraPermissionDesc = "扫描文档需要使用设备的相机权限。",
                grantPermission = "授予相机权限",
                copyText = "复制文本",
                singleMode = "单张",
                batchMode = "批量",
                importFiles = "导入文件",
                importImages = "导入图片",
                exitAppTitle = "退出 FinalPDF？",
                exitAppSubtitle = "您确定要退出应用程序吗？",                exitAppConfirm = "Exit App",
                selectFromLibrary = "Choose from Local Library",
                internalStorage = "Internal Storage",
                processSuccess = "Process completed successfully!",
                fileSavedInFinalPDF = "File saved successfully in FinalPDF folder",
                autoSystem = "Auto (System)",
                verticalScroll = "Vertical Scroll",
                horizontalScroll = "Horizontal Scroll",
                portraitMode = "Portrait",
                landscapeMode = "Landscape",
                useSystemBrightness = "使用系统亮度",
                lockPdfTitle = "加密并锁定 PDF",
                lockPdfDesc = "使用密码保护文档",
                unlockPdfTitle = "解锁并移除 PDF 密码",
                unlockPdfDesc = "移除加密 PDF 的密码保护",
                confirm = "确认",
                noPdfSelected = "未选择 PDF 文件",
                noPdfFound = "未找到 PDF 文件"
            )
            else -> AppStrings( // "ar" and default
                home = "الرئيسية",
                documents = "المستندات",
                tools = "الأدوات",
                settings = "الإعدادات",
                goodMorning = "صباح الخير!",
                goodEvening = "مساء الخير!",
                welcomeMessage = "مرحباً بك في تطبيق FinalPDF",
                statsTitle = "إحصائيات المكتبة",
                sortTitle = "ترتيب الملفات",
                searchPlaceholder = "بحث في ملفات PDF...",
                recent = "الأخيرة",
                favorites = "المفضلة",
                allDocs = "كل المستندات",
                emptyLibraryTitle = "مكتبتك فارغة حالياً",
                emptyLibrarySubtitle = "اضغط على زر الإضافة (+) لفتح وقراءة أول ملف PDF لك.",
                noSearchResultsTitle = "لم نجد نتائج بحث مطابقة",
                noSearchResultsSubtitle = "تأكد من كتابة اسم الملف بشكل صحيح وجرب مجدداً.",
                totalFiles = "إجمالي الملفات",
                favoriteFiles = "المفضلة",
                openedFiles = "الملفات المفتوحة",
                readingHours = "ساعات القراءة",
                missingFiles = "مفقودة من الهاتف",
                totalPdfs = "مستندات PDF",
                totalFolders = "مجلدات",
                documentSize = "حجم المستندات",
                libraryOverviewSubtitle = "نظرة عامة على ملفات ومؤشرات القراءة في مكتبتك",
                sampleFiles = "ملفات تجريبية",
                pdfFiles = "ملفات PDF",
                folders = "المجلدات",
                sampleDocumentTitle = "الملف التجريبي (14 صفحة)",
                importedDocuments = "مستندات مستوردة",
                unknown = "غير معروف",
                fileCountFormat = { count -> "$count ملف" },
                toolsTitle = "أدوات PDF المتقدمة",
                toolsSubtitle = "أدوات ذكية لتعديل وتخصيص مستنداتك وحفظها فوراً",
                cameraOcrTitle = "ماسح الكاميرا الضوئي (Camera OCR)",
                cameraOcrDesc = "تصوير ومسح المستندات واستخراج النصوص فوراً",
                cloudOcrTitle = "تحويل PDF إلى نص (OCR)",
                cloudOcrDesc = "تحويل الصفحات المصورة إلى نص قابل للتعديل",
                mergePdfTitle = "دمج ملفات PDF",
                mergePdfDesc = "دمج عدة ملفات في مستند واحد جديد",
                splitPdfTitle = "تقسيم ملف PDF",
                splitPdfDesc = "استخراج صفحات محددة لملف جديد",
                compressPdfTitle = "ضغط ملف PDF",
                compressPdfDesc = "تصغير حجم الملف مع الحفاظ على الجودة",
                rotatePdfTitle = "تدوير الصفحات",
                rotatePdfDesc = "تغيير اتجاه صفحات معينة أو جميع الصفحات",
                reorderPdfTitle = "إعادة ترتيب الصفحات",
                reorderPdfDesc = "سحب وإعادة تنظيم ترتيب صفحات الملف",
                deletePdfTitle = "حذف الصفحات",
                deletePdfDesc = "حذف صفحات غير مرغوبة من ملف PDF",
                appearanceSection = "تخصيص المظهر (APPEARANCE)",
                appThemeTitle = "مظهر التطبيق",
                appLanguageTitle = "لغة التطبيق والتعرف (App Language)",
                showToolsTabTitle = "إظهار تبويب الأدوات",
                showToolsTabSubtitle = "إظهار أو إخفاء تبويب الأدوات في الشريط السفلي",
                readerDisplaySection = "إعدادات القارئ والشاشة (READER & DISPLAY)",
                scrollDirectionTitle = "اتجاه التمرير",
                defaultZoomTitle = "مستوى الزووم الافتراضي",
                doubleTapZoomTitle = "تكبير النقر المزدوج (Double Tap)",
                readingThemeTitle = "مظهر خلفية القراءة",
                sortSubtitle = "اختر طريقة تنظيم واستعراض ملفات الـ PDF الخاصة بك",
                sortAlphabetical = "أبجدي",
                sortAlphaAsc = "أ -> ي  ↑",
                sortAlphaDesc = "ي -> أ  ↓",
                sortFileSizeLabel = "حجم الملف",
                sortSizeAsc = "الأصغر أولاً  ↑",
                sortSizeDesc = "الأكبر أولاً  ↓",
                sortDateAddedLabel = "تاريخ الإضافة",
                sortDateAsc = "الأقدم أولاً  ↑",
                sortDateDesc = "الأحدث أولاً  ↓",
                quickActions = "إجراءات سريعة",
                addToFav = "إضافة إلى المفضلة",
                removeFromFav = "إزالة من المفضلة",
                addToFavDesc = "حفظ الملف في المفضلة للوصول السريع",
                removeFromFavDesc = "إزالة من قائمة الملفات المفضلة",
                selectFile = "تحديد الملف",
                selectFileDesc = "تفعيل وضع التحديد المتعدد لهذا الملف",
                shareFile = "مشاركة الملف",
                shareFileDesc = "إرسال ملف الـ PDF للتطبيقات الأخرى",
                renameFile = "إعادة تسمية",
                renameFileDesc = "تغيير اسم الملف أو عنوان المستند",
                fileInfo = "معلومات الملف",
                fileInfoDesc = "عرض خصائص ومواصفات وتفاصيل الملف",
                deleteFile = "حذف الملف",
                deleteFileDesc = "حذف الملف نهائياً من الهاتف أو المكتبة",
                openDocument = "فتح المستند",
                share = "مشاركة",
                copyPath = "نسخ المسار",
                pathCopied = "تم نسخ مسار الملف للحافظة",
                fullPath = "المسار الكامل:",
                folderName = "اسم المجلد",
                storageLocationSection = "موقع الملف والتخزين",
                pdfVersion = "إصدار الـ PDF",
                encryption = "التشفير والأمان",
                encrypted = "محمي بكلمة مرور",
                notEncrypted = "غير محمي",
                authorSection = "تفاصيل المؤلف والمستند",
                authorLabel = "المؤلف / الكاتب",
                documentTitleLabel = "عنوان المستند",
                subjectLabel = "الموضوع",
                keywordsLabel = "الكلمات المفتاحية",
                datesSection = "التواريخ والوقت",
                creationDate = "تاريخ الإنشاء",
                modificationDate = "تاريخ آخر تعديل",
                creatorAppSection = "البرنامج المنشئ والمحرك",
                creatorLabel = "البرنامج المنشئ",
                producerLabel = "محرك التصدير",
                extractingMetadata = "جاري استخراج بيانات المستند والميتاداتا...",
                pagesTab = "الصفحات",
                viewTab = "العرض",
                zoomTab = "الزووم",
                themesTab = "السمات",
                bookmarkTab = "إشارة",
                moreTab = "أدوات",
                searchInPdf = "البحث في المستند",
                jumpToPage = "الانتقال لصفحة",
                tableOfContents = "فهرس المحتويات",
                readAloud = "القراءة الصوتية (TTS)",
                autoScroll = "التمرير التلقائي",
                cropPages = "قص الصفحات",
                ocrExtract = "استخراج النص (OCR)",
                notesHighlights = "الملاحظات والتظليل",
                exportImage = "تصدير كصورة",
                printDocument = "طباعة المستند",
                fitWidth = "ملاءمة العرض",
                fitPage = "ملاءمة الصفحة",
                actualSize = "100% الحجم الأصلي",
                themeLight = "خلفية بيضاء",
                themeDark = "الوضع الليلي",
                themeSepia = "سيبيا دافئ",
                themeAmoled = "أسود داكن (OLED)",
                goButton = "انتقال",
                closeButton = "إغلاق",
                cancelButton = "إلغاء",
                saveButton = "حفظ",
                confirmButton = "تأكيد",
                cameraPermissionTitle = "إذن الكاميرا مطلوب",
                cameraPermissionDesc = "يتطلب الماسح الضوئي الوصول إلى كاميرا الجهاز لتصوير المستندات وقراءتها.",
                grantPermission = "منح إذن الكاميرا",
                copyText = "نسخ النص",
                singleMode = "فردي",
                batchMode = "دفعة",
                importFiles = "استيراد ملفات",
                importImages = "استيراد صور",
                exitAppTitle = "الخروج من FinalPDF؟",
                exitAppSubtitle = "هل أنت تأكد من رغبتك في الخروج من التطبيق؟",                exitAppConfirm = "Exit App",
                selectFromLibrary = "Choose from Local Library",
                internalStorage = "Internal Storage",
                processSuccess = "Process completed successfully!",
                fileSavedInFinalPDF = "File saved successfully in FinalPDF folder",
                autoSystem = "Auto (System)",
                verticalScroll = "Vertical Scroll",
                horizontalScroll = "Horizontal Scroll",
                portraitMode = "Portrait",
                landscapeMode = "Landscape",
                useSystemBrightness = "استخدام سطوع النظام التلقائي",
                lockPdfTitle = "تشفير وقفل ملف PDF",
                lockPdfDesc = "حماية المستند بكلمة سر لمنع التعديل والفتح غير المصرح به",
                unlockPdfTitle = "فك قفل وإزالة حماية PDF",
                unlockPdfDesc = "إزالة كلمة السر والتشفير من مستند مشفر",
                confirm = "تأكيد",
                noPdfSelected = "لم يتم اختيار ملف بعد",
                noPdfFound = "لا توجد ملفات PDF متوفرة حالياً"
            )
        }
    }
}

fun getLocalizedFileName(fileName: String, strings: AppStrings): String {
    return when (fileName) {
        "الملف التجريبي (14 صفحة)", "Sample Document (14 pages)", "book_14_pages" -> strings.sampleDocumentTitle
        else -> fileName
    }
}

fun getLocalizedFolderName(folderName: String, strings: AppStrings): String {
    return when (folderName) {
        "ملفات تجريبية", "Sample Files" -> strings.sampleFiles
        "مستندات مستوردة", "Imported Documents" -> strings.importedDocuments
        "غير معروف", "Unknown" -> strings.unknown
        "المستندات", "Documents" -> strings.allDocs
        else -> folderName
    }
}
